### ISSUE TITLE
Implement Assistant API for RAG

### ISSUE THREAD

**Issue by PrinceBaghel258025** [Technoculture/echoes#45]
- [ ] Assistant id on the org level (default: echoes-orgslug, ex: echo-exrna)
- [ ] some kind of evaluation test for knowledge base (allows users to upload csv containing MCQ's to test the reliability of knowledge base

---

- [ ] Adding knowledge base
- [ ] use user access permission for allowing to add data to knowledge base

**Comment by sutyum** [comment]
closed by #61
